version: '3'

services:

  mauticdb:
    image: percona/percona-server
    hostname: mauticdb
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Password@123
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    networks:
      - traefik-public

  mautic:
    image: mautic/mautic
    hostname: mautic
    links:
      - mauticdb:mysql
    depends_on:
      - mauticdb
    volumes:
      - mautic_data:/var/www/html
    environment:
      - MAUTIC_DB_HOST=mauticdb
      - MYSQL_PORT_3306_TCP=3306
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=Password@123
      - MAUTIC_DB_NAME=mautic
      - MAUTIC_RUN_CRON_JOBS=true
      - MAUTIC_CRON_HUBSPOT=Enables
    networks:
      - traefik-public
    deploy:
      labels:
        traefik.http.routers.mautic-https.tls: 'true'
        traefik.http.routers.mautic-https.rule: Host(`mautic.bbytegroup.com`)
        traefik.http.routers.mautic-https.tls.certresolver: le
        traefik.http.routers.mautic-https.entrypoints: https
        traefik.http.routers.mautic-http.middlewares: https-redirect
        swarmpit.service.deployment.autoredeploy: 'true'
        traefik.constraint-label: traefik-public
        traefik.http.routers.mautic-http.rule: Host(`mautic.bbytegroup.com`)
        traefik.http.routers.mautic-http.entrypoints: http
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.services.mautic.loadbalancer.server.port: '80'

volumes:
  mysql_data:
    driver: local
  mautic_data:
    driver: local
networks:
  traefik-public:
    external: true