version: '3'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=bonglv@Password
      - MSSQL_PID=Enterprise
    networks:
      - traefik-public
    ports:
      - 33333:1433
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2048M
        reservations:
          cpus: '0.05'
          memory: 32M
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
networks:
  traefik-public:
    external: true